
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: martijn-cnpg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mwallet/martijn-test.git
    targetRevision: main
    path: clusters/dev/databases/martijn
  destination:
    server: https://kubernetes.default.svc
    namespace: dbaas-onte-martijn-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
