{% if values.create_argocd_application %}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.cluster_name }}-cnpg
  namespace: ${{ values.argocd_namespace }}
spec:
  project: ${{ values.argocd_project }}
  source:
    repoURL: https://${{ values.repo_url | replace("github.com?owner=", "github.com/") | replace("&repo=", "/") }}.git
    targetRevision: ${{ values.manifest_branch }}
    path: ${{ values.manifest_path }}/${{ values.cluster_name }}
  destination:
    server: ${{ values.destination_server }}
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{% endif %}