apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: martijn-cnpg
  title: martijn CNPG
  description: CNPG GitOps manifests for martijn
  tags:
    - cnpg
    - postgres
    - openshift
    - gitops
    - 
  annotations:
    github.com/project-slug: mwallet/martijn-test
spec:
  type: database
  lifecycle: experimental
  owner: group:platform-team
  system: postgres-platform