apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: martijn
  namespace: dbaas-onte-martijn-test
  labels:
    app.kubernetes.io/name: martijn
    app.kubernetes.io/managed-by: backstage
    env: 
spec:
  instances: 2

  imageName: >-
    ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 5Gi
    storageClass: crc-csi-hostpath-provisioner



  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: app
      owner: app
