apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: martijn
  namespace: dbaas-onte-martijn-test
  labels:
    app.kubernetes.io/name: martijn
    app.kubernetes.io/managed-by: backstage
    env: 
spec:
  instances: 1

  imageName: >-
    ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 5Gi
    storageClass: ocs-external-storagecluster-ceph-rbd

{% if values.extension_mode == 'geo-imagevolume' and values.enable_postgis %}
  postgresql:
    extensions:
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:18
          ld_library_path:
            - system
{% endif %}

  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: app
      owner: app
{% if values.enable_postgis %}
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
{% if values.enable_pgrouting %}
        - CREATE EXTENSION IF NOT EXISTS pgrouting;
{% endif %}
{% endif %}