{% if values.create_pooler %}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: ${{ values.cluster_name }}-pooler
  namespace: ${{ values.namespace }}
spec:
  cluster:
    name: ${{ values.cluster_name }}
  instances: ${{ values.pooler_instances }}
  type: rw
  pgbouncer:
    poolMode: ${{ values.pool_mode }}
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
{% endif %}